### ISSUE TITLE
About future plan

### ISSUE THREAD

**Issue by rhcproc** [hayesall/babybear#1]
Hi, This project is suitable for others.
If this project can operate with scikit-learn, it will be more helpful.
Do you have any plans to support scikit-learn?

**Comment by hayesall** [comment]
That's a neat idea!

The data layout is pretty different between this, pandas, and numpy: so I think it would involve quite a few tweaks to get scikit-learn to dispatch on a DataFrame like this.

The "everything is a string" pattern make it difficult to apply scikit-learn methods generally, but objects for categorical data could be a good place to start (trees, CategoricalNB, etc.)

**Comment by rhcproc** [comment]
thank you
I'm a bit interested in scikit-learn.
Gradually, it seems that libraries such as pandas and scikit-learn are getting heavier.
I think some people want to use the library in a limited space.
So I fully support this dataframe project.
Personally, I'm going to bring some of the scikit-learn modules and configure a small class.
If there's anything I need to check (e.g. scikit-learn dataframe tests), please let me know.
